# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
tls: 
  email: "peter.schenkel@storyxag.com"

pvc: 
 storageClass: nextcloud
 size: 30Gi
nodeSelector: {}

tolerations: []

affinity: {}
