apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deployment
spec:
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud-container
        image: nextcloud
        volumeMounts:
          - mountPath: "/var/www/html"
            name: nextcloud-data
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/hostname: india634
      volumes:
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-pvc
