apiVersion: v1
kind: Service
metadata:
  name: ldap
spec:
  type: ClusterIP 
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: ldap
    port: 389
    targetPort: 389
    protocol: TCP
  - name: ldaps
    port: 636
    targetPort: 636
    protocol: TCP
  selector:
    app: ldap
