apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: {{ .Values.pvc.storageClass.ldap.name }}
  resources:
    requests:
      storage: {{ .Values.pvc.storageClass.ldap.size }} 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpldap-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: {{ .Values.pvc.storageClass.phpldap.name }}
  resources:
    requests:
      storage: {{ .Values.pvc.storageClass.phpldap.size }}
