apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ldap-cert
  namespace: default
spec:
  secretName: ldap-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: ldap.storyx.company
  dnsNames:
  - ldap.storyx.company
